name: List Available macOS Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  list-installers:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: List Installers
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate
          softwareupdate --list-full-installers
      - name: Skipped Job Explanation
        if: github.repository != 'Comp-Labs/Download-macOS'
        run: echo "The 'Send Report' job is skipped because it's running on a forked repository. It can run only on the original repository - Comp-Labs/Download-macOS"
  re-run-failed-jobs:
    runs-on: ubuntu-latest
    needs: [list-installers]
    if: always() && (needs.list-installers.result == 'failure')
    steps:
      - name: Needs Context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: echo "$NEEDS_CONTEXT"
